FROM python:3.8

RUN cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime
RUN echo 'Asia/Taipei' > /etc/timezone

RUN apt-get update && apt-get install -y vim file make
RUN pip3 install pyyaml

RUN echo "alias ll='ls -al'" >>  /root/.bashrc
RUN echo "alias vi='vim'" >>  /root/.bashrc
